import Head from "next/head";
import Image from "next/image";
import styles from "../styles/pages/Home.module.scss";
import { Button, Card } from "../proton";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Button>Button Example</Button>

				<Button.Group>
					<Button emphasis="primary">Button Example</Button>
					<Button hollow underline emphasis="secondary">
						Button Example
					</Button>

          <Card>
            
          </Card>
				</Button.Group>
			</main>
		</div>
	);
}
